[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
hydrogen = "GeFoFS8vqoYQwcoRqLDxeg4TqEFxf3vMCGHMPV8u9rr5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/volkovivan/.config/solana/id.json"

[scripts]
test = "yarn ts-mocha -p ./tsconfig.json -t 1000000 tests/**/pipeline.test.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "0.0.0.0"
url = "https://api.mainnet-beta.solana.com"
ledger = ".anchor/test-ledger"
rpc_port = 8899
