[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
h2u_contracts = "53CP3kVEC2YnSd3ionqHRNeJ9ZheeBgghogRjPtkcjPr"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/petroyaremenko/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
